--- #잔디체커 설정 파일. 이건 양식파일입니다. 쓰기 전에, 파일 이름을 settings_form.yaml 이 아닌 settings.yaml 으로 바꿔야 합니다.

# 토큰
token: 토큰번호 기입

# 스케쥴러 실행 주기 설정을 위한 CRON 문자열
cron: 0 1 0 1/1 * ? * # ← ㅁ매일 0시 1분

# 스케쥴러가 실행될 대상 채널 ID
targetChannelId: 1234567890...

# 추적 명단
members: [
  [daanta, daanta-real],
  [test, test]
]